### PR TITLE
Updated the versions

### PR DESCRIPTION
**Pull request by callmehalpha**
php
node
docker-compose

### CODE REVIEW

**Comment by lephleg** [comment]
Thanks for this @President-Temitope. Will review shortly.

**Comment by callmehalpha** [comment]
> Thanks for this @President-Temitope. Will review shortly.

Alright. Also the installation is stuck at a section where on chooses city.

**Comment by lephleg** [comment]
@President-Temitope update your fork with my latest commits in order for your new versions to work as intended.

**Comment by callmehalpha** [comment]
> @President-Temitope update your fork with my latest commits in order for your new versions to work as intended.

okay

**Pull request merged**
